---
title: "Demo File"
author: "Johannes Cunow"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Demo File}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  knitr::opts_chunk$set(include = TRUE, message = FALSE)
)

```


## Load libraries
```{r install package, message=FALSE, warning=FALSE }
# ## Install MinirhizotronR package
# if (!require("devtools")) {
#   install.packages("devtools")
# }
# devtools::install_github("jcunow/MinirhizotronR")
# library(MinirhizotronR)
# 
# ## other libraries
# library(dplyr);library(ggplot2)
```


## Setup
```{r setup }
# track runtime
t00 = Sys.time()


library(MinirhizotronR)
library(tidyverse)

# Directory
seg.path = "C:/Users/jocu0013/Desktop/Oulanka/Scans_FullSegmented/Oulanka2023_03/"
rgb.path = "C:/Users/jocu0013/Desktop/Oulanka/Scans_Blended/Full/Oulanka2023_03/"
cal.path = "C:/Users/jocu0013/Desktop/Oulanka/Data/"
im.ls = list.files(seg.path)
rgb.im.ls = list.files(rgb.path)

```


## Tube Calibrations
```{r  calibration }

### Action !!! (consider if the soil starts later Tape, unit is cm!)
# If the Tubes have been calibrated; otherwise soil start has to be assumed
s0 = read.csv(paste0(cal.path ,"OulankaTubeInsertionAngle.csv"))
s0$soil0 = s0$Soil.Excess 

## alternativly
#s0 = data.frame(soil0 = 0, InsertionAngle = 45)
#r0 = 2320/2 # image center row/ upside of the tube

tube.thicc = 7 # cm diameter
dpi = 300

```


## The Loop
```{r main loop body}

# bundeled in a function - not strictly necessary
image.analysis.loop = function(){
  # loop counter
k=0
l=0
# depth slice interval in cm
interval.scalar  = 1
# storage
#root.frame = data.frame(depth = seq(-10,99, interval.scalar))
root.list  = list()

for (i in im.ls) {
  t0 = Sys.time()

  # counter to go through each row of soil 0cm and insertion angle calibration data (in-situ)
  if(nrow(s0) > 1){
    k=k+1
  }else{
    k=1
  }

  # counter
  l = l+1

  # load image
  im =  terra::rast(paste0(seg.path,i))
  # load rgb image
  j = rgb.im.ls[l]
  rgb.im =  terra::rast(paste0(rgb.path,j))
  # ensure 3 dimensions, fails if alpha channel is at 1
  if(dim(im)[3]>3){
    im = im[[1:3]]
  }
  if(dim(rgb.im)[3]>3){
    rgb.im = rgb.im[[1:3]]
  }

  ## mask has not included regions as NA, if everything is ought to be used than mask == rootpic -> TRUE
  mask = im[[2]]
  mask = terra::t(mask)
  if(terra::global(im,"max",na.rm=TRUE)$max[2] > 1){
    im = im[[2]]/255
  }else{
    im = im[[2]]
  }



  ### determine rotation center
  r0 = RotationE(rgb.im)
  #r0 = dim(im)[1]/2
  center.offset = round(r0  / (dim(im)[1]-r0),3) # 1 means the tube upside in perfectly in the middle of the image

  # rotation censoring (if rotation center between timepoints differs OR edge effects are present)
  im = RotCensor(img = im,center.offset = center.offset, fixed.rotation = T, fixed.width = 2100)



  ### adjust to however your naming convention works !!!!
  Tube.name =  paste0("T", stringr::str_sub(i,start= -8,end= -6))

  tape.excess = round(SoilSurfE(rgb.im)/300*2.54, 3)$soil0
  soil.start = s0$soil0[k] + (tape.excess)
  # Phase shifted sine depth map
  DepthMap = create.depthmap(im = im, 
                             mask = mask,
                             dpi = dpi,
                             sinoid = T,
                             start.soil = soil.start,
                             center.offset = center.offset,
                             tilt = s0$InsertionAngle[k],
                             tube.thicc = tube.thicc)


  ## prep root skeleton
  im.skeleton =  skeletonize_image(im,methods = "MAT",layer=2)


  ## deep-neighbour angle (interesting by itself but here just used for root length estimation)
  dem = -DepthMap *  1/interval.scalar
  dem[terra::t(im.skeleton) != 1] <- NA
  angles = terra::terrain(dem,v = "flowdir")
  angles = terra::subst(angles, from = c(0, 1, 2, 4, 8, 16, 32, 64, 128), to = c( NA, 90,135,180,225,270,315,0,45))
  orth.map = angles == 0 | angles == 90 | angles == 180 | angles == 270
  diag.map = angles == 45 | angles == 135 | angles == 225 | angles == 315
  orth.map = terra::t(orth.map)
  diag.map = terra::t(diag.map)

  # create Depthmap and control intervals
  DepthMap = terra::t(DepthMap) * 1/interval.scalar
  terra::ext(DepthMap) = terra::ext(im)
  bm = binning(depthmap = DepthMap,nn = interval.scalar, round.option = "rounding" )

  # roots and background
  rootpixel = terra::zonal(im,bm,"sum",na.rm=TRUE)
  rootpixel[,1] = rootpixel[,1] * interval.scalar
  # background <- inversion of roots
  void = im
  terra::values(void) = 1-terra::values(im)
  voidpixel = terra::zonal(void,bm, "sum",na.rm=TRUE)
  voidpixel[,1] = voidpixel[,1] * interval.scalar

  # root length
  terra::ext(orth.map) <- terra::ext(bm)
  terra::ext(diag.map) <- terra::ext(bm)

  kimura.sum.orth = terra::zonal(orth.map,bm, "sum", na.rm = TRUE)
  kimura.sum.diag = terra::zonal(diag.map,bm, "sum", na.rm = TRUE)
  rootlength = round(( kimura.sum.diag[,2]**2 + (kimura.sum.diag[,2] + kimura.sum.orth[,2]/2)**2 )**0.5   + kimura.sum.orth[,2]/2)
  rootlength = round( rootlength / (dpi/2.54), 4)

  roots = merge(rootpixel,voidpixel,by = colnames(rootpixel)[1])
  colnames(roots) = c("depth","rootpx","voidpx")
  roots$rootlength = rootlength
  roots$Tube = Tube.name

  # store info from loop round
  root.list[[l]] = roots


  # progress indicator
  t1 = Sys.time()
    cat('\r',paste0(which(im.ls == i)," out of ",length(im.ls)), " - It took",round(difftime(t1,t0,units ="secs"),1)," secs\n \n ")
    flush.console()

  if(which(im.ls == i) == length(im.ls)){
    cat('\r',length(im.ls)," images processed! Get yourself a cookie!", " - It took",round(difftime(t1,t00,units ="mins"),1)," mins\n " )
  }

}
}

### run funtion ###
# uncomment to run:

# image.analysis.loop()


```

```{r include=FALSE}
# data.path =  "C:/Users/jocu0013/Documents/DemoData/"
# load(paste0(data.path,".rda"))
```


## Reshape the data
```{r reshape}
# root.frame2 = array2DF( array(root.list))
# root.frame2$Var1 = NULL
# colnames(root.frame2) <- c("depth","root_px","void_px","rootlength","Tube")
# root.frame2$Plot = stringr::str_sub(root.frame2$Tube,start = 3) %>% as.numeric()
# # clean
# root.frame2$depth = ifelse(is.nan(root.frame2$depth), NA, root.frame2$depth)
# root.frame2$root_px = ifelse(is.nan(root.frame2$root_px), NA, root.frame2$root_px)
# root.frame2$void_px = ifelse(is.nan(root.frame2$void_px), NA, root.frame2$void_px)
# root.frame2$rootlength = ifelse(is.nan(root.frame2$rootlength), NA, root.frame2$rootlength)
# root.frame2$Tube = ifelse(is.nan(root.frame2$Tube), NA, root.frame2$Tube)
# # calc
# root.frame2$rootcover.percent =  root.frame2$root_px / (root.frame2$void_px + root.frame2$root_px)
# root.frame2$rootlength.percent =  root.frame2$rootlength / (root.frame2$void_px + root.frame2$root_px) * (dpi/2.54)**2
# root.frame2$thicc = root.thickness(root.frame2$rootlength, root.frame2$root_px)


```



## Compare Rooting Distributions
```{r distribution comparison}
# P = root.frame2 %>% filter(Plot == 37)  %>%  mutate(rxprob = root_px / sum(root_px,na.rm = TRUE)) #%>% select(rxprob)
# Q = root.frame2 %>% filter(Plot == 39)  %>% mutate(rxprob = root_px / sum(root_px,na.rm = TRUE)) #%>% select(rxprob)
# 
# modP = loess(data = P, formula = rxprob ~depth,span=0.5)
# modQ = loess(data = Q, formula = rxprob ~depth,span=0.5)
# 
# P$sRX = predict(modP)
# Q$sRX = predict(modQ)
# 
# P$sRX = P$sRX / sum(P$sRX)
# Q$sRX = Q$sRX / sum(Q$sRX)
# 
# Pcut = P$sRX[1:min(c(length(P$rxprob),length(Q$rxprob)))]
# Qcut = Q$sRX[1:min(c(length(P$rxprob),length(Q$rxprob)))]
# 
# 
# MinirhizotronR::tail_weighted_wasserstein_distance(Pcut,Qcut, method = "constant", inverse = FALSE)
# tail_weighted_js_divergence(Pcut, Qcut, method = "constant", inverse = FALSE)
# plot(Q$rxprob,type = "l"); points(P$rxprob,col = "red",type = "line")

```




### Plot Output
```{r plotting, fig.cap="Root pixel per area"}
# plot root cover
# root.frame2 %>%
#   ggplot(aes(depth,rootcover.percent)) +
#   geom_point()+
#   geom_smooth(span=0.5,se=F,size = 1)+
#   theme_classic()+
#   theme(legend.position  = c(0.8,0.8))+
#   ggtitle("Root Cover Distribution")

```




